# Generated by Django 5.0.3 on 2024-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='promotiontable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(max_length=100)),
                ('seniority', models.CharField(max_length=100)),
                ('assesments', models.CharField(max_length=100)),
                ('time_sence', models.CharField(max_length=100)),
                ('elgibility', models.CharField(max_length=10)),
            ],
        ),
    ]
